/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root endpoint
         * @description Legacy root endpoint that returns a simple message
         */
        get: operations["getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the current health status of the service including database connectivity. This is the proper health check endpoint. No authentication required.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sync/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get CSRF token
         * @description Returns a new CSRF token and sets the CSRF cookie. This endpoint is public and can be used to bootstrap the authentication flow.
         */
        get: operations["getCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sync/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create workspace and sync code
         * @description Creates a new workspace, session, and generates a permanent reusable sync code. This is the first step for new users to create their workspace.
         */
        post: operations["enableSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sync/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pair with existing workspace
         * @description Connects to an existing workspace using a sync code. The sync code is reusable and does not expire. Creates a new session for the workspace.
         */
        post: operations["pair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sync/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current session info
         * @description Returns information about the current authenticated session
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sync/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout current session
         * @description Revokes the current session and clears session cookies
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sync/code/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate sync code
         * @description Generates a new sync code for the workspace, invalidating the previous one. The new code is returned in the response.
         */
        post: operations["rotateCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sync/sessions/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke all sessions
         * @description Revokes all active sessions for the current workspace, then clears the current browser cookies.
         */
        post: operations["revokeSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workspace snapshot
         * @description Returns the current workspace snapshot containing beans, machines, and brews. The snapshot includes version information for optimistic concurrency control.
         */
        get: operations["getSnapshot"];
        /**
         * Update workspace snapshot
         * @description Updates the workspace snapshot with new data. Uses If-Match header for optimistic concurrency control to prevent overwriting changes.
         */
        put: operations["putSnapshot"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Service health status with dependency checks */
        HealthStatus: {
            /**
             * @description Overall health status
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "unhealthy";
            /**
             * Format: date-time
             * @description When the health check was performed
             * @example 2025-01-01T00:00:00.000Z
             */
            timestamp: string;
            /**
             * @description API version
             * @example 0.2.0
             */
            version: string;
            /** @description Individual health checks */
            checks: {
                database: components["schemas"]["DatabaseHealth"];
            };
        };
        /** @description Database connectivity health check */
        DatabaseHealth: {
            /**
             * @description Database connection status
             * @example up
             * @enum {string}
             */
            status: "up" | "down";
            /**
             * @description Error message if database is down
             * @example null
             */
            message?: string;
        };
        CsrfResponse: {
            /**
             * @description Indicates if CSRF is required for subsequent requests
             * @example true
             */
            csrfRequired: boolean;
            /**
             * @description Current CSRF token
             * @example abc123def456
             */
            csrfToken: string;
        };
        SyncRequest: {
            /**
             * @description Permanent reusable workspace sync code
             * @example ABCD1234
             */
            code: string;
        };
        EnableSyncResponse: {
            /**
             * @description Unique identifier for the created workspace
             * @example 1
             */
            workspaceId: number;
            /**
             * @description Permanent sync code for the workspace
             * @example ABCD1234
             */
            syncCode: string;
            /**
             * @description CSRF token for the new session
             * @example abc123def456
             */
            csrfToken: string;
        };
        PairResponse: {
            /**
             * @description Indicates successful connection
             * @example true
             */
            connected: boolean;
            /**
             * @description Unique identifier for the workspace
             * @example 1
             */
            workspaceId: number;
            /**
             * Format: date-time
             * @description Expiration timestamp for the session
             * @example 2025-01-01T00:00:00.000Z
             */
            expiresAt: string;
            /**
             * @description CSRF token for the new session
             * @example abc123def456
             */
            csrfToken: string;
        };
        SessionInfo: {
            /**
             * @description User ID (workspace owner)
             * @example 1
             */
            sub: number;
            /**
             * @description Current session ID
             * @example session-uuid-string
             */
            sessionId: string;
            /**
             * @description Workspace ID
             * @example 1
             */
            workspaceId?: number;
        };
        RotateCodeResponse: {
            /**
             * @description New sync code for the workspace
             * @example NEWCODE123
             */
            syncCode: string;
        };
        /** @description Complete workspace data */
        Snapshot: {
            /** @enum {number} */
            schemaVersion: 1;
            beans: components["schemas"]["Bean"][];
            machines: components["schemas"]["Machine"][];
            brews: components["schemas"]["Brew"][];
        };
        SnapshotResponse: {
            snapshot: components["schemas"]["Snapshot"];
            /**
             * @description Current snapshot version for concurrency control
             * @example 0
             */
            version: number;
        };
        /** @description Coffee bean record */
        Bean: {
            /** @description Stable client-generated ID, unique per entity type */
            localId: string;
            name: string;
            /** @description 0-5 */
            rating: number;
            roastLevel: number;
            origin: string[];
            process: string[];
            variety: string[];
            brand: string;
            flavors: string[];
            /** @enum {string} */
            status: "Excellent" | "Good" | "Mid" | "Horrible" | "New" | "";
            /** @enum {string} */
            dominantNote: "Fruity" | "Nutty" | "Floral" | "Sweet" | "Sour" | "Spices" | "Roasted" | "Green" | "";
            /** @enum {string} */
            botanic: "Arabica" | "Robusta" | "";
            /** @enum {string} */
            designation: "Pure Origin" | "Blend" | "";
            finished: boolean;
        };
        /** @description Coffee machine or equipment record */
        Machine: {
            /** @description Stable client-generated ID, unique per entity type */
            localId: string;
            name: string;
            brand: string;
            type: string;
            purchaseDate: string;
            model: string;
            grindRange: string;
            capacity: string;
        };
        /** @description Coffee brew record; bean/machine reference snapshot localIds */
        Brew: {
            /** @description Stable client-generated ID, unique per entity type */
            localId: string;
            /** @description Bean localId */
            beanLocalId?: string;
            /** @description Machine localId */
            machineLocalId?: string;
            beanWeight: number;
            espressoWeight: number;
            grindSize: number;
            overallRating?: number;
            /** @description -5 sour/under-extracted to +5 bitter/over-extracted */
            tasteScore?: number;
            /** @description -5 weak to +5 strong */
            strengthScore?: number;
            extractionTime?: string;
            flow?: string;
            /** @description ISO 8601 date-time */
            date: string;
        };
        ErrorResponse: {
            /**
             * @description HTTP status code
             * @example 400
             */
            statusCode: number;
            /**
             * @description Error message
             * @example Bad Request
             */
            message: string;
            /**
             * @description Error type
             * @example Bad Request
             */
            error: string;
        };
    };
    responses: {
        /** @description Unauthorized - no valid session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "statusCode": 401,
                 *       "message": "Unauthorized",
                 *       "error": "Unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden - invalid or missing CSRF token */
        CsrfInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "statusCode": 403,
                 *       "message": "Invalid CSRF token",
                 *       "error": "Forbidden"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Current snapshot version for optimistic concurrency control */
        IfMatch: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token generated */
            200: {
                headers: {
                    /** @description Contains the CSRF cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    enableSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description No body required, but CSRF validation is performed */
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Workspace and session created */
            201: {
                headers: {
                    /** @description Contains session and CSRF cookies */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnableSyncResponse"];
                };
            };
            403: components["responses"]["CsrfInvalid"];
        };
    };
    pair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Session created for existing workspace */
            201: {
                headers: {
                    /** @description Contains session and CSRF cookies */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            403: components["responses"]["CsrfInvalid"];
            /** @description Sync code not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully logged out */
            204: {
                headers: {
                    /** @description Clears session cookies */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    rotateCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New sync code generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateCodeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions revoked */
            204: {
                headers: {
                    /** @description Clears session cookies */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current workspace snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Workspace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putSnapshot: {
        parameters: {
            query?: never;
            header: {
                /** @description Current snapshot version for optimistic concurrency control */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Snapshot"];
            };
        };
        responses: {
            /** @description Snapshot updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Invalid snapshot data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Workspace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Snapshot version conflict - data has changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const healthStatusStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["HealthStatus"]["status"]> = ["healthy", "unhealthy"];
export const databaseHealthStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["DatabaseHealth"]["status"]> = ["up", "down"];
export const snapshotSchemaVersionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Snapshot"]["schemaVersion"]> = [1];
export const beanStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Bean"]["status"]> = ["Excellent", "Good", "Mid", "Horrible", "New", ""];
export const beanDominantNoteValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Bean"]["dominantNote"]> = ["Fruity", "Nutty", "Floral", "Sweet", "Sour", "Spices", "Roasted", "Green", ""];
export const beanBotanicValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Bean"]["botanic"]> = ["Arabica", "Robusta", ""];
export const beanDesignationValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Bean"]["designation"]> = ["Pure Origin", "Blend", ""];
